apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: tomcat
  namespace: fleet-default
spec:
  branch: master
  insecureSkipTLSVerify: false
  paths:
  - /multi-cluster/tomcat
  repo: https://github.com/polinchw/fleet-examples.git
  targetNamespace: tomcat
  targets:
  - clusterGroup: bill-group
type: fleet.cattle.io.gitrepo
