apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: tomcat
  namespace: fleet-local
spec:
  branch: master
  insecureSkipTLSVerify: false
  paths:
  - /multi-cluster/tomcat
  repo: https://github.com/polinchw/fleet-examples.git
type: fleet.cattle.io.gitrepo
