apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: fleet-example
  namespace: fleet-default
spec:
  branch: master
  insecureSkipTLSVerify: false
  paths:
  - /multi-cluster/helm
  repo: https://github.com/rancher/fleet-examples.git
  targetNamespace: test1
  targets:
  - clusterGroup: bill-group
type: fleet.cattle.io.gitrepo
